KOKKOS_SETTINGS=KOKKOS_SRC_PATH=/lustre/atlas/scratch/arghyac/csc205/summit_miniapp/miniapp_ronnie/kokkos/kokkos CXX=g++ KOKKOS_DEVICES=OpenMP KOKKOS_ARCH=Power8 GTEST_PATH=/lustre/atlas/scratch/arghyac/csc205/summit_miniapp/miniapp_ronnie/kokkos/kokkos/tpls/gtest KOKKOS_OPTIONS=compiler_warnings KOKKOS_PATH=/lustre/atlas/scratch/arghyac/csc205/summit_miniapp/miniapp_ronnie/kokkos/kokkos

all:
	$(MAKE) -f /lustre/atlas/scratch/arghyac/csc205/summit_miniapp/miniapp_ronnie/kokkos/kokkos/containers/unit_tests/Makefile KOKKOS_SRC_PATH=/lustre/atlas/scratch/arghyac/csc205/summit_miniapp/miniapp_ronnie/kokkos/kokkos CXX=g++ KOKKOS_DEVICES=OpenMP KOKKOS_ARCH=Power8 GTEST_PATH=/lustre/atlas/scratch/arghyac/csc205/summit_miniapp/miniapp_ronnie/kokkos/kokkos/tpls/gtest KOKKOS_OPTIONS=compiler_warnings KOKKOS_PATH=/lustre/atlas/scratch/arghyac/csc205/summit_miniapp/miniapp_ronnie/kokkos/kokkos

test: all
	$(MAKE) -f /lustre/atlas/scratch/arghyac/csc205/summit_miniapp/miniapp_ronnie/kokkos/kokkos/containers/unit_tests/Makefile KOKKOS_SRC_PATH=/lustre/atlas/scratch/arghyac/csc205/summit_miniapp/miniapp_ronnie/kokkos/kokkos CXX=g++ KOKKOS_DEVICES=OpenMP KOKKOS_ARCH=Power8 GTEST_PATH=/lustre/atlas/scratch/arghyac/csc205/summit_miniapp/miniapp_ronnie/kokkos/kokkos/tpls/gtest KOKKOS_OPTIONS=compiler_warnings KOKKOS_PATH=/lustre/atlas/scratch/arghyac/csc205/summit_miniapp/miniapp_ronnie/kokkos/kokkos test

clean:
	$(MAKE) -f /lustre/atlas/scratch/arghyac/csc205/summit_miniapp/miniapp_ronnie/kokkos/kokkos/containers/unit_tests/Makefile KOKKOS_SRC_PATH=/lustre/atlas/scratch/arghyac/csc205/summit_miniapp/miniapp_ronnie/kokkos/kokkos CXX=g++ KOKKOS_DEVICES=OpenMP KOKKOS_ARCH=Power8 GTEST_PATH=/lustre/atlas/scratch/arghyac/csc205/summit_miniapp/miniapp_ronnie/kokkos/kokkos/tpls/gtest KOKKOS_OPTIONS=compiler_warnings KOKKOS_PATH=/lustre/atlas/scratch/arghyac/csc205/summit_miniapp/miniapp_ronnie/kokkos/kokkos clean
